[GOOGLE_APPLICATION_CREDENTIALS_JSON]
type = "service_account"
project_id = "liquid-tractor-462013-t5"
private_key_id = "5ae504e7fe20f49421d052e4f653206a19fd650d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD4DHUPYt/52CB8
FTSMipC1MPfoE9KqFYGdVvd7UPCOhj8ZrcWpZ0RTU2r7D//kMijAbEZ7dsHMoTre
D7fYZu2fyRHLeWOq/cLxkBTzmfoi3m+GTTMjN11vnUY5Km81dE7DsEhYy9JTt4gf
cHAeMsnq+md1kcIEf049/yS6frB5fGwd+4n6m74ICzoxsAFah8wSJjADQPWa6z0o
7H/tNasnEIHYM/YXhu/Oa8XqHsko3reTAcjObbOvkIo+K3b1vIWdYgHVnIHvxxp/
ZtZJyiB7+lkehuB0jgoPHslcVrq23dOHenst7lyz7k8XeP4NIKexp3e2917tgfDA
nD2U5pvhAgMBAAECggEACvLb0OXLnpbSWj/CXci4+fJzItiLJixEWBpQWq5YK+ZT
jzHbJW7UNnxaXsIWSK+JGnM9CjKT+9ELDOWzNvdWGkUxBqLxSgkg63IxZo4/mv3n
/MzYCsAlHOnbgWb02S5s0pjrnJXEjyLs/HxFSqPxwzAx1F/uaS3oWXazW5L/faEw
0j5jf4JH/zallPwG+4dGdiDaGWDjqJ4b+sBxj22m3YbP3iSdMrV/GqyRcwG1p764
vXDocCOdDuXnhxOFSvWmKPvGYq0vBfGop3ET9gzrHyAZpKpBLimCeUolk/LTDykt
WF3Bj3WV917ZmHXHzzsY6JjZRPfkDNAgzhOS/GnFJQKBgQD+s1D95x6nzkL3pkYP
6H6UQH65wFoFQquEkb4Ac1dCcweT4H6OXx4d6lOJncnJGHJpKoUY+uHNGlIP4Oya
UY1l27wd9z89c9ee9u0d6/Nm2+bxYgLZzLj3Csiej/twM/IwRmJ0Nct4I6dyvms8
Ies8sfm5OyrriXvUPskXIFp7fQKBgQD5UHPVpf40HbdJXo7qbVhQL7Lm9tFXnseO
NnYK2SOndDwibaHzKcd2Ql+CUJwujSBa3zFdRsmLKhl4fEJve16z6TZDOoF9Sbgp
xmck9phuFtG9HNTtEK9AelvjEBwaexyeza9GeBFr1dRkiiLoFQgjrMzt0tfufoj8
9kDhj7cnNQKBgBaNdC93RoyfQ+i/zVZdRNAFwfLaqF3s4FkVupg5nlFg9BvQ9gPP
QlBtzkXSNerbgk3zmON0W4gYu4lyZiDn9bg+M7MHkI71cfM+dBKBMQU7lYBsKEp2
yS3+w3Le1unBf8Fsig02MjUKGyqa1830RusR60XOimdevhs2EAI/OCPVAoGBAMHA
HzUS+hmgWldfb+uJLI+scfkCKTBRyb2gX14Q3598Olt7HdeuST+DV1wbrzSSImnc
eC2IHIrVHdQ/pRWkJ7XjcHMQnZ8zUjbM5E2agl1TyI2SQXs2cyvFq3ErjNubf2N+
b09xcgB+vb+ghn4cEiY/XUcZiwviNC16ZnOkz25dAoGBAM2G08X2IcT2PWLgS8pq
AntBLi/XqkkuDnCTTwemx+A8cdQNQ206sp26ooQHiVQ+Ax5hnzrBq088ATpf2ScF
lThxi2uJMBsHpBERa3gQsqr55yUyWT/8kxFTNwM//y7dJBHWKp/vRXsrYykcMqTq
tJ+ynb7TXVgGXuX2AyqQW232
-----END PRIVATE KEY-----"""
client_email = "wypadki-uploader@liquid-tractor-462013-t5.iam.gserviceaccount.com"
client_id = "102028476377763605876"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/wypadki-uploader%40liquid-tractor-462013-t5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
